foreground #ebfafa
background #0d1116
selection_foreground #ffffff
selection_background #314154

cursor #ffffff
cursor_text_color #0d1116

active_border_color #37f499
inactive_border_color #3b2d6b

active_tab_background #37f499
active_tab_foreground #0d1116
inactive_tab_background #3b2d6b
inactive_tab_foreground #ebfafa

color0 #0d1116
color1 #f16c75
color2 #37f499
color3 #f1fc79
color4 #5fa9f4
color5 #987afb
color6 #04d1f9
color7 #ebfafa
color8 #7081d0
color9 #ff7c86
color10 #69f8b3
color11 #f6ffb0
color12 #82b8ff
color13 #b39dfc
color14 #66e4fd
color15 #ffffff
